#!/usr/bin/env bash
# Merge / Nightly / Release：唯一发布门禁（CI quality job 执行）
set -euo pipefail
cd "$(dirname "$0")/.."
bash scripts/check.sh
go mod verify
staticcheck ./...
govulncheck ./...
go test -race -count=1 ./...
go test -cover ./internal/...
echo "FULL CHECKS PASSED"
